---
  version: 1
  schedule: 
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow: 
    collect: 
      metrics: 
        /intel/procfs/meminfo/mem_free: {}
        /intel/procfs/meminfo/mem_total: {}
      config:
        /intel/procfs/load:
          "proc_path": "/var/procfs"
      publish:
        - 
          plugin_name: "influxdb"
          config: 
             host: "influxdb"
             port: 8086
             database: "test"
             user: "admin"
             password: "admin"
             https: false
             skip-verify: false
