---
  version: 1
  schedule: 
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow: 
    collect: 
      metrics: 
        /intel/mock/foo: {}
        /intel/mock/bar: {}
        /intel/mock/*/baz: {}
      config: 
        /intel/mock: 
          name: "root"
          password: "secret"          
      publish: 
        - 
          plugin_name: "influxdb"
          config: 
             host: "influxdb"
             port: 8086
             database: "test"
             user: "admin"
             password: "admin"
