version: '2'
services:
  golang:
    container_name: golang_${GOLANGVER}
    image: intelsdi/gvm:latest
    volumes:
      - ${PLUGIN_SRC}:/snap-plugin-publisher-influxdb
      - /proc:/var/procfs
    links:
      - influxdb
  influxdb:
    container_name: influxdb
    image: influxdb:${INFLUXDB_VERSION}-alpine
    environment:
      PRE_CREATE_DB: "test"
    expose:
      - "8083"
      - "8086"      