version: '2'
services:
  golang:
    container_name: golang_${GOLANGVER}
    image: intelsdi/gvm:latest
    volumes:
      - ${PLUGIN_SRC}:/snap-plugin-publisher-influxdb
      - /proc:/var/procfs
    links:
      - influxdb
  influxdb:
    container_name: influxdb
    image: tutum/influxdb
    environment:
      UDP_DB: "test"
    expose:
      - "8083"
      - "8086"    
      - "4444/udp"  