---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: influxdb-deployment
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: influxdb
        spec:
            containers:
            - name: influxdb
              image: influxdb:0.13-alpine
              imagePullPolicy: "IfNotPresent"
              ports:
              - containerPort: 8083
              - containerPort: 8086
            - name: main
              image: intelsdi/snap:alpine_test
              imagePullPolicy: "Always"
              env:
                - name: SNAP_VERSION
                  value: "latest"

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  ports:
  - name: http-api
    port: 8086
    targetPort: 8086
    protocol: TCP
  - name: http-web
    port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: influxdb
  sessionAffinity: None
  type: NodePort
