---
.travis.yml:
  sudo: true
  services:
    - docker
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE=small
      - TEST_TYPE=medium
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: K2AnEm2FcP0wEQ1rWJzkASpLUBHeICjwFxYGiq44HB3KTj/4G4MYtSIxYjWdG9C81sfCbC+wMHyWla8rRrVOxeMTBeJpoBNoX8wo3gAwetfA3DkVyN51xTsiHUa7yhjDjxD9scrGsJlwO+d9zyk63RU9rQGKxoDudlBvtfEat+Uke6Oq0rcUSXzqBF9ejLwscLYlFTmz+NfeACcvVqsB1Ht5RpR/VuqFXwpfmj/G+3YBx6RYQQempltL+JZUzT8UhHpQJf2sp148i/T/jqM4Agwmu398G61Jeu3t7ESDnvA37t+1hmmDq88AOveEp3pbOThCS/4ycbL2DRRns6aQnrZgBbVvHxY/ZdSWsyjVbqBQJCguo4BF0hyDdnfSi8mbkwcRf9XSSftwHxW0NyWPYhg/GASf2lKsrGG7UGZoUmMgb/jJ03sEdwjqzB+ICDa+Txhhmikxgwqfj0hyDXbHYmPNSwQ5TYI35upiEj8X8fERceFYgKGUCmphqsKtZq4iPcdKqJ4xBtHmKLutk2YqkDuKPUrx96/3kSTTF8OfaSU3+bipFcOyo48TLc/QEaag4MRoPU+L47xRwlSrZFFFrioVmFjxgY8yOoN0yRuc9XccMmmEzApa621OlzMjyduMw8UG5/+tXcmOOlcM1n2p+RqtJ/Vi0/9oyG7AxeP4mj8=
    api_key:
      secure: ozKcVu2076vJtKde0osjHcaTFl7lcy0XEqr9AZ6VeZ5EOWCvxxj/z+XOX3ocunUrdPpbyJtjPSUBUwFfbsbE7fSzCMSJDcSQkFgNm3xSmvRFf78/c2Z6B4DEuq0F8dM1+vsDd1hEW6VIC+gNj263a34JtdfYNH/+rpKvqsMgK93J7yQoImUaZz9gnaifatydvOBiqbffDyx7lJj9ikXGMG383upnGngoXk1O19qRW1xZeIG5JLoJF8HnCT+YMx2L7vUZ/Indbm8C8Eacoy631prkPcJbMg1Wf0t7hGSa61P2wCZf/+04bbimt6hvImA+8Oc4pRxXgZLJ6a3nT9MMQvNCICWeBqzmMoaTo69Y6jP+RUdARYYOC4VTEd8NPAdtqWJbH1RCFF6oeMm4m+urgQDwuVwml/Mqegww+T2yjuUmpUGSK1fn6C268T4HV+PzZK8eYkd0BNjOaFuycZ1D76mia0dW4QTjPfK9CzydV+rduM/wjQvytJ8D+FK/CEI7AZepnCpabDu5nwYSipsEW4O5pKYMOhL6cv6B+LhKYQ6YnKlYURJ9qer0iKUHbet38N8y12EI1Ew2yOZcnlRdHzoeUolx/oaF8kXRkc+TcUvuypSoPSHfRMuIP3xJ9KCbC5u90afm7HPuYFn+WvJFryg4MxeJnpIYdZTk/3pKLGo=
