sudo: false
language: go
go:
- 1.4.2
- 1.5
before_install:
- cp .netrc ~
- chmod 600 .netrc
- go get github.com/tools/godep
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get -u github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/vet
- go get golang.org/x/tools/cmd/goimports
- go get github.com/smartystreets/goconvey/convey
- if [ ! -d $PULSE_PLUGIN_SOURCE ]; then mkdir -p $HOME/gopath/src/github.com/intelsdi-x; ln -s $TRAVIS_BUILD_DIR $PULSE_PLUGIN_SOURCE; fi # CI for forks not from intelsdi-x
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
env:
  global:
    - PULSE_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/intelsdi-x/pulse-plugin-publisher-influxdb
install:
- export TMPDIR=$HOME/tmp
- mkdir -p $TMPDIR
- cd $PULSE_PLUGIN_SOURCE # change dir into source
- make deps
script:
- make check 2>&1 # Run test suite
notifications:
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
